# ==============================================================================
# DATABASE MODULE - TRAEFIK ROUTERS
# ==============================================================================
# Description: Traefik dynamic router definitions for the database module
# Author: Matt Barham
# Created: 2026-02-13
# Modified: 2026-04-21
# Version: 1.0.1
# Host: Your Server
# ==============================================================================
# Type: Traefik Dynamic Config (routers)
# Component: module: database
# ==============================================================================

http:
  routers:
    couchdb:
      rule: Host(`couchdb.{{ env "DOMAIN" }}`)
      entryPoints: "websecure"
      middlewares: chain-couchdb@file
      service: couchdb-svc@file
      priority: 100

    minio:
      rule: Host(`minio.{{ env "DOMAIN" }}`)
      entryPoints: "websecure"
      middlewares: chain-no-auth@file
      service: minio-console-svc@file

    influxdb3-api:
      rule: Host(`db3.{{ env "DOMAIN" }}`)
      entryPoints: "websecure"
      middlewares: chain-influxdb3-api@file
      service: influxdb3-svc@file
