# ==============================================================================
# DATABASE MODULE - TRAEFIK SERVICES
# ==============================================================================
# Description: Traefik dynamic service definitions for the database module
# Author: Matt Barham
# Created: 2026-02-13
# Modified: 2026-04-21
# Version: 1.0.1
# Host: Your Server
# ==============================================================================
# Type: Traefik Dynamic Config (services)
# Component: module: database
# ==============================================================================

http:
  services:
    couchdb-svc:
      loadBalancer:
        servers:
          - url: http://couchdb:5984

    minio-console-svc:
      loadBalancer:
        servers:
          - url: http://minio:9090

    minio-svc:
      loadBalancer:
        servers:
          - url: http://minio:9000

    influxdb3-svc:
      loadBalancer:
        servers:
          - url: http://influxdb3:8181
